name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Implementation Guide
        run: |
          wget https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar
          docker run -v $(pwd):/home/publisher/ig ghcr.io/fhir/ig-publisher-gh java -jar publisher.jar -ig .

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./output

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
